---
language: python
services:
  - docker
env:
  matrix:
    - MOLECULE_DISTRO="fedora:28"
    - MOLECULE_DISTRO="fedora:29"
install:
  - pip install molecule docker
  # workaround until https://github.com/ansible/molecule/issues/1727 is fixed
  - pip uninstall -y testinfra
  - pip install testinfra
script:
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule syntax
  - molecule test
